name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: build
        run: |
          pnpm i --frozen-lockfile
          pnpm build

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: build
        run: |
          pnpm i --frozen-lockfile
          pnpm typecheck

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: build
        run: |
          pnpm i --frozen-lockfile
          pnpm format-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: build
        run: |
          pnpm i --frozen-lockfile
          pnpm lint

